//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuyitosWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public decimal N_BOLETA { get; set; }
        public string PRODUCTO { get; set; }
        public decimal PRECIO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal TOTAL { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal VENTAS_FK { get; set; }
    
        public virtual REGISTRO_VENTAS REGISTRO_VENTAS { get; set; }
    }
}
