//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuyitosWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.FIADO1 = new HashSet<FIADO>();
        }
    
        public string RUT_CLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public decimal TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string DIRECCION { get; set; }
        public string FIADO { get; set; }
        public decimal COMUNA_FK { get; set; }
        public decimal REGION_FK { get; set; }
        public decimal VENTAS_FK { get; set; }
    
        public virtual ICollection<FIADO> FIADO1 { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual REGISTRO_VENTAS REGISTRO_VENTAS { get; set; }
    }
}
