//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuyitosWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIADO
    {
        public decimal ID_FIADO { get; set; }
        public string ESTADO { get; set; }
        public string PRODUCTO { get; set; }
        public decimal VALOR { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal TOTAL { get; set; }
        public System.DateTime FECHA { get; set; }
        public string CLIENTE_FK { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
