//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuyitosWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_PEDIDO
    {
        public ORDEN_PEDIDO()
        {
            this.RECEPCION = new HashSet<RECEPCION>();
        }
    
        public decimal ID_PEDIDO { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public decimal CANTIDAD { get; set; }
        public string ESTADO { get; set; }
        public decimal PRODUCTO_FK { get; set; }
        public string PROVEEDOR_FK { get; set; }
    
        public virtual ICollection<RECEPCION> RECEPCION { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
