//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuyitosWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.ORDEN_PEDIDO = new HashSet<ORDEN_PEDIDO>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public string RUT_PROVEEDOR { get; set; }
        public string NOMBRE_PROVEEDOR { get; set; }
        public decimal TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string DIRECCION { get; set; }
        public decimal RUBRO_FK { get; set; }
        public decimal COMUNA_FK { get; set; }
        public decimal REGION_FK { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<ORDEN_PEDIDO> ORDEN_PEDIDO { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual RUBRO RUBRO { get; set; }
    }
}
