//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuyitosWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCION
    {
        public decimal N_RECEPCION { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal TOTAL { get; set; }
        public decimal ORDEN_FK { get; set; }
        public decimal PRODUCTO_FK { get; set; }
    
        public virtual ORDEN_PEDIDO ORDEN_PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
