//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuyitosWeb.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBFAMILIA
    {
        public SUBFAMILIA()
        {
            this.TIPO_PRODUCTO = new HashSet<TIPO_PRODUCTO>();
        }
    
        public decimal ID_SUBFAMILIA { get; set; }
        public string NOMBRE_SUBFAMILIA { get; set; }
        public decimal FAMILIA_FK { get; set; }
    
        public virtual FAMILIA_PRODUCTO FAMILIA_PRODUCTO { get; set; }
        public virtual ICollection<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
    }
}
